### ISSUE TITLE
Add b-hread name to "Warning: B-thread is blocking an event it is also requesting, this may lead to a deadlock."

### ISSUE THREAD

**Issue by geraw** [bThink-BGU/BPjs#103]

**Comment by geraw** [comment]
Maybe it would be better if an implicit request would override the blocking: `{request: X, block: bp,all}` means block all but the event `X` that I am requesting.

**Comment by michbarsinai** [comment]
Don't think so. Too much magic-y. B-Programmers should know what they request and what they block :-)

**Comment by geraw** [comment]
> Don't think so. Too much magic-y. B-Programmers should know what they request and what they block :-)

Agreed, but blocking all but my event is a common pattern that requiring a lengthy definition of an add-hoc event filter. Maybe an idiom such as `myEventFiler.except(X)` would help?

**Comment by michbarsinai** [comment]
True. We currently have `bp.allExcept(es)` where `es` is an event set. Seems to me this does not scale beyond simple programs, since it's enough that two b-threads use is on a different `es`, and the b-program deadlocks.

There might be a nice design patterns there, where "all except" means "all the events I care about, except". Like strict LSCs.
(Out of current scope, though).
