### ISSUE TITLE
Make BPjs POM version available at runtime

### ISSUE THREAD

**Issue by michbarsinai** [bThink-BGU/BPjs#136]
This should probably be added to the BPjs class as a static method.

**Comment by ananyak19** [comment]
Hi, I would like to work on this, can you please guide me on how to get started.

**Comment by michbarsinai** [comment]
Thanks!

Clone the project. Add the method to the BPjs class (https://github.com/bThink-BGU/BPjs/blob/develop/src/main/java/il/ac/bgu/cs/bp/bpjs/BPjs.java) as a static method.

I'm not sure about the actual method of getting the current data from the POM, but that knowledge should be available around the internets, since BPjs just a regular Maven project.

**Comment by ananyak19** [comment]
Hi @michbarsinai , I have created a Pull request- [https://github.com/bThink-BGU/BPjs/pull/207](url). 

First I checked whether maven-jar-plugin in POM.xml file is properly configured or not. i.e, addDefaultImplementationEntries should be set to true. Since it was set to true, I proceeded with the java code and added  a new method getPomVersion. 
Please check whether it is okay or not. 
Thanks.

**Comment by michbarsinai** [comment]
PR is #207

**Comment by ananyak19** [comment]
Hey, @michbarsinai I have made the changes as suggested by you. Please review.. Thanks! :)
